### ISSUE TITLE
Scala 2.13.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [scalate/scalate#133]
- [x] <del> https://github.com/scalatra/scalamd/pull/5 </del> https://github.com/scalatra/scalamd/pull/6

**Comment by xuwei-k** [comment]
https://github.com/scalate/scalate/pull/152

**Comment by seratch** [comment]
Scalate 1.9.0 is already available for Scala 2.13.0-M4. We'll work on M5 releases soon.

**Comment by xuwei-k** [comment]
> #171 almost done. some tests still fail 😢

created another issue https://github.com/scalate/scalate/issues/197
