### ISSUE TITLE
scala 2.12 in play-scalate?

### ISSUE THREAD

**Issue by edrevo** [scalate/scalate#137]
It looks like play-scalate already has the necessary commits to support scala 2.12, but no release has been made that cross-compiles with that version.

Could you create a 0.4.0 release of play-scala which adds support for 2.12?

**Comment by seratch** [comment]
will do

**Comment by seratch** [comment]
@edrevo 
I just released 0.4.0 for Scala 2.11 and 2.12.

* https://github.com/scalate/play-scalate/releases/tag/0.4.0
* https://oss.sonatype.org/content/repositories/releases/org/scalatra/scalate/play-scalate_2.12/
