### ISSUE TITLE
Replace the JSON parser

### ISSUE THREAD

**Issue by magnolia-k** [scalate/scalate#183]
```
[warn] /xxxx/xxxxx/scalate/scalate-core/src/test/scala/org/fusesource/scalate/mustache/MustacheJSONTest.scala:45:7: object JSON in package json is deprecated (since 1.0.6): Use The Scala Library Index to find alternatives: https://index.scala-lang.org/
[warn]       JSON.parseFull(jsonText) match {
[warn]       ^
```
However, since there is no JSON library corresponding to SCALA 2.13.0-M4 yet, replace it when the corresponding library is released.

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/com/typesafe/play/play-json_2.13.0-M4/
- https://repo1.maven.org/maven2/org/json4s/json4s-core_2.13.0-M4/
- https://repo1.maven.org/maven2/io/spray/spray-json_2.13.0-M4/
