### ISSUE TITLE
Update changelog.md

### ISSUE THREAD

**Issue by ngocdaothanh** [scalate/scalate#198]
The last version mentioned in [changelog](https://github.com/scalate/scalate/blob/master/changelog.md) is "Scalate 1.6.1, released 2012-12-29".

Please mention later versions (at least 1.9.0):
https://github.com/scalate/scalate/releases

Without the changelog info, I'm not sure why I should update Scalate in my project.

**Comment by seratch** [comment]
Okay, I will work on it later.

**Comment by seratch** [comment]
I've done it. https://github.com/scalate/scalate/commit/299a179332c06bf18498f7367426ab118881b9d3

**Comment by ngocdaothanh** [comment]
Many thanks for the great work!
