### ISSUE TITLE
Scala 2.13.0-M5

### ISSUE THREAD

**Issue by xuwei-k** [scalate/scalate#199]
- [x] https://github.com/scalatra/scalamd/pull/12
- [x] https://github.com/scala/scala-xml/issues/256
- [x] https://github.com/scalatest/scalatest/issues/1409

**Comment by seratch** [comment]
https://oss.sonatype.org/content/repositories/releases/org/scalatra/scalate/scalamd_2.13.0-M5/

**Comment by xuwei-k** [comment]
😢 

- https://github.com/xuwei-k/scalate/commit/812cfbd2efbf5caaf3ea827489938c0cd8218bcb
- https://travis-ci.org/xuwei-k/scalate/jobs/429128574

```
[error]/home/travis/build/xuwei-k/scalate/scalate-core/src/main/scala/org/fusesource/scalate/support/ScalaCompiler.scala:70:37: value printMessage is not a member of scala.tools.nsc.reporters.ConsoleReporter
[error]        case FakePos(fmsg) => super.printMessage(posIn, msg);
[error]                                    ^
[error]/home/travis/build/xuwei-k/scalate/scalate-core/src/main/scala/org/fusesource/scalate/support/ScalaCompiler.scala:71:34: value printMessage is not a member of scala.tools.nsc.reporters.ConsoleReporter
[error]        case NoPosition => super.printMessage(posIn, msg);
[error]                                 ^
[error]/home/travis/build/xuwei-k/scalate/scalate-core/src/main/scala/org/fusesource/scalate/support/ScalaCompiler.scala:74:17: value printMessage is not a member of scala.tools.nsc.reporters.ConsoleReporter
[error]          super.printMessage(posIn, msg);
[error]                ^
[error]/home/travis/build/xuwei-k/scalate/scalate-core/src/main/scala/org/fusesource/scalate/support/ScalaCompiler.scala:93:18: value printSummary is not a member of ScalaCompiler.this.LoggingReporter
[error]        reporter.printSummary()
[error]                 ^
[warn]three warnings found
[error]four errors found
[error](scalate-core / Compile /compileIncremental) Compilation failed
```

**Comment by seratch** [comment]
Maybe, we should use `display` method instead from now on.

* https://github.com/scala/scala/commit/043c5ad21150ff0f1c72053d5c2cf91fa6adf081#diff-9548fb92d7a016fecc0dedf1c988de2a
* https://github.com/scala/scala/blob/v2.13.0-M5/src/compiler/scala/tools/nsc/reporters/ConsoleReporter.scala

**Comment by magnolia-k** [comment]
- printMessage is a method called from display
 - printMessage changed to private method

In other words, it is not good to override printMessage and it is not good to call display, so should we override display?

**Comment by seratch** [comment]
Implementating an overridden method of `#display` seems to be straight-forward. I will release 1.9.1-RC1 including the change if the CI builds for #203 succeed.

**Comment by seratch** [comment]
@SethTisue Yes, I already published. I forgot closing this issue. https://search.maven.org/artifact/org.scalatra.scalate/scalate-core_2.13.0-M5/1.9.1-RC1/jar
