### ISSUE TITLE
Scala 3 (Dotty) migration

### ISSUE THREAD

**Issue by seratch** [scalate/scalate#253]
I'm sorry to say this but I myself don't have time and motivation to work on Scala 3 (Dotty) migration. We're looking for people that are interested in making necessary efforts for it.

**Comment by mccartney** [comment]
Forgive my ignorance - the effort would mostly be about making it compile with Scala 3, right?

**Comment by mccartney** [comment]
Also most (?) of the work seems to be already done in #566

**Comment by mccartney** [comment]
Not sure what is missing then.

Maybe just release what we have?

**Comment by seratch** [comment]
@mccartney Thanks for flagging this. v1.10, which was released just a few minutes ago, is available for both Scala 2 and 3! The implementation for Scala 3 may still have remaining issues, but they can be resolved moving forward.

**Comment by mccartney** [comment]
Thank you.
