### ISSUE TITLE
release 1.9.6

### ISSUE THREAD

**Issue by magnolia-k** [scalate/scalate#267]
The following issues should be resolved since the support for Scala 2.13.2 has been completed.

https://github.com/scalate/scalate/issues/262

https://github.com/scalate/scalate/commit/6d224ad631374d0d9c5577d5f08b35f4a5d50ca6

It should be released as 1.9.6.

**Comment by pjfanning** [comment]
@magnolia-k I tested the latest scalate code including https://github.com/scalate/scalate/commit/6d224ad631374d0d9c5577d5f08b35f4a5d50ca6 and it works with scala 2.12.11, 2.13.1 and 2.13.2

**Comment by magnolia-k** [comment]
@seratch 
Release, please!

**Comment by seratch** [comment]
I'm working on this now.

**Comment by seratch** [comment]
I've finished publishing all the jar files onto Sonatype OSS repositories. The version will be available also in Maven Central repositories within a few hours at the latest.

**Comment by seratch** [comment]
I just shipped the sbt plugin as well. https://github.com/scalate/sbt-scalate-precompiler/compare/1.9.5.0...1.9.6.0
