### ISSUE TITLE
Maven -> sbt migration? (Unified Scala 2.10 / 2.11 source tree + cross compilation)

### ISSUE THREAD

**Issue by arashi01** [scalate/scalate#68]
Now that we're no longer tied to the Fuse Maven infrastructure it may be a good idea to consider migrating to sbt to avoid having to maintain multiple branches for each supported Scala version; and avoid tons of xml build config.

I currently have a working example (see https://github.com/scalate/scalate/compare/scala_2.11...arashi01:the_great_sbt_migration) based on the scala_2.11 branch however also supporting scala_2.10 from the same sources. This includes all projects which could easily be ported from Maven to sbt.  Those which could not (i.e. depend on Maven as a tool or the maven-scalate-plugin which does not have a full featured sbt equivalent) have been split into their own git repositories:
- [maven-scalate-plugin](https://github.com/arashi01/maven-scalate-plugin) - Cannot build with sbt!
- [scalate-archetypes](https://github.com/arashi01/scalate-archetypes) - Cannot build with sbt!
- [scalate-samples](https://github.com/arashi01/scalate-samples) - No proper sbt equivalent of maven-scalate-plugin (site generation features) ... yet
- [scalate-distro](https://github.com/arashi01/scalate-distro) - Has dependencies out of scope of sbt build (eg archetypes).

All projects compile, and all tests pass for both Scala 2.10 and 2.11.

If there is an interest in pursuing this, I'll also attempt to get the above Maven projects compiling as standalone projects (will need a parent POM).

Note: scalate-website has not been converted to sbt due to dependency on maven-scalate-plugin sitegen. Not sure how best to handle this.

**Comment by rossabaker** [comment]
I would love to see this. I've been struggling to publish a patch release due to some undiagnosed bit rot in the Maven build since the last release. An sbt build would make this project a lot friendlier to new contributors.

**Comment by arashi01** [comment]
Great!  Have a working parent POM locally tested with scalate-maven-plugin as a standalone build.  Will be working on getting the remaining standalone Maven projects building as well (scalate-samples, scalate-archetypes, scalate-distro) over the next couple of days.

The main Scalate project sbt build is ready for testing/review. Thinking that a new master branch (based on scala_2.11) may be a good idea going forward so I can submit a pull request. It will also ensure we don't break scala_2.11 or scala_2.10 until properly tested.

**Comment by xuwei-k** [comment]
+1

**Comment by arashi01** [comment]
Just to update, a first cut at a standalone Scalate parent POM can be seen at [scalate-pom][1].  The following Maven projects are successfully building (and tested) as standalone projects:
- [scalate-maven-plugin][2]
- [scalate-archetypes][3]: Unified scala_2.10 and scala_2.11 branches by adding `scalaBinaryVersion` and `scalaPatchVersion` properties for use during project generation, and replacing all hard coded references with an appropriate property.
- [scalate-samples][4]: Single branch, built against default Scala version provided by `scalate-pom`. Samples not running correctly via `mvn jetty:run` are `scalate-sample-spring-mvc` and `scalate-example`; however seems to be isses with the actual samples rather than build.

[1]: arashi01/scalate-pom
[2]: arashi01/scalate-maven-plugin
[3]: arashi01/scalate-archetypes
[4]: arashi01/scalate-samples

**Comment by rossabaker** [comment]
Fantastic!  

There are going to be some merge conflicts because I had to update the version when doing the 1.7.1 release.  (Sadly, Maven complains about inheriting version from a property, so it's repeated frequently.)  If you want to merge into your working copy, great; otherwise, we can take care of the conflicts at pull request time.

**Comment by arashi01** [comment]
Had to focus on the day job a bit!

No worries, have replayed the changes against the 2.10 branch anyway since it has fewer merge commits cluttering the history.  Will be putting in a pull request against 2.10 shortly.

With regard to the remaining projects, the scalate-distro build relies on too many hard coded relative paths from the main build to be easily transformed to a stand-alone project. I haven't yet been able to figure out how to get Maven to checkout multiple git repositories to copy files from.  It will probably be easier to port to an sbt built using sbt-native-packager, and I'll be looking into that shortly.

Have also been working on a [fresh sbt plugin][1] for pre-compilation as well as site generation. This should allow all projects except `scalate-maven-plugin` and `scalate-archetypes` to build via sbt. The plugin relies on a couple of additional `scalate-tool` commands written for this purpose.

[1]: https://github.com/arashi01/sbt-scalate

**Comment by xuwei-k** [comment]
should be close this?

**Comment by seratch** [comment]
yes, we can close this now.
