### ISSUE TITLE
String Temple

### ISSUE THREAD

**Issue by sirinath** [scalate/scalate#70]
Can you support String Template. Scalasti use to support it but now unmaintained.

**Comment by magnolia-k** [comment]
Scalasti is now well maintained

https://github.com/bmc/scalasti/commits/master

**Comment by magnolia-k** [comment]
Since then, maintenance has not been continued (Scala 2.13 is also not supported), so this issue will be closed for now.

If you need Scalasti support, the first thing you need to do is to update Scalasti.

If you need support, please reopen this issue.
