### ISSUE TITLE
support Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [scalate/scalate#83]

**Comment by seratch** [comment]
That's right, it's about time to consider. I'd like to work on this.

**Comment by seratch** [comment]
We need to publish scalamd in advance. https://github.com/scalatra/scalamd/pull/1

**Comment by seratch** [comment]
scalamd is mostly ready (just waiting for specs2 release).

I found another issue that we need to upgrade ScalaTest to 3.0.0 because ScalaTest 2.x doesn't support Scala 2.12.0 builds. Existing tests on Scalate cannot compile with ScalaTest 3.0 as-is. We need to migrate not a few tests then.

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/org/scalatra/scalate/scalate-core_2.12/1.8.0-RC1/
