### ISSUE TITLE
[doc] It is impossible to get Scalate tool

### ISSUE THREAD

**Issue by gaydenko** [scalate/scalate#97]
Hi!
This page http://scalate.github.io/scalate/documentation/getting-started.html says how to get Scalate tool refering this URL: http://scalate.github.io/scalate/documentation/installing.html The URL results in 404.

**Comment by samouille666** [comment]
Same experience and a bit frustrated.

**Comment by seratch** [comment]
Scalate tool is no longer supported. We should remove the part.

**Comment by magnolia-k** [comment]
@seratch 
Where is it written that the Scalate tool is no longer supported? If not, create an issue and make a PR to delete.

**Comment by seratch** [comment]
>Where is it written that the Scalate tool is no longer supported?
Not described at all.

> If not, create an issue and make a PR to delete.
Yes, please.

**Comment by magnolia-k** [comment]
If there is anything else that has stopped maintenance, I will make an issue.
